// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/api/comment/[id].ts";
import * as $3 from "./routes/api/comment/downvote/[id].ts";
import * as $4 from "./routes/api/comment/upvote/[id].ts";
import * as $5 from "./routes/api/joke.ts";
import * as $6 from "./routes/api/secret/[id].ts";
import * as $7 from "./routes/api/secret/delete/[id].ts";
import * as $8 from "./routes/api/secret/index.ts";
import * as $9 from "./routes/index.tsx";
import * as $10 from "./routes/new.tsx";
import * as $11 from "./routes/search.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/api/comment/[id].ts": $2,
    "./routes/api/comment/downvote/[id].ts": $3,
    "./routes/api/comment/upvote/[id].ts": $4,
    "./routes/api/joke.ts": $5,
    "./routes/api/secret/[id].ts": $6,
    "./routes/api/secret/delete/[id].ts": $7,
    "./routes/api/secret/index.ts": $8,
    "./routes/index.tsx": $9,
    "./routes/new.tsx": $10,
    "./routes/search.tsx": $11,
  },
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
